name: Node.js CI

on:
  push:
    branches: [ master ]
jobs:
  frontend-test :
    name: Frontend Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.1
        cache: 'npm'
        cache-dependency-path: my-app/package-lock.json
    - name: Tests
      run: npm ci
      working-directory: my-app
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}

      - name: Prettify code
        run: npx prettier --check
        working-directory: my-app
